version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: medical-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_medica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: medical-api-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      # Se utiliza el nombre del servicio 'db' para la red interna de Docker
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestion_medica?schema=public
      JWT_SECRET: chacalito
    depends_on:
      - db
    # Se añade espera de 10s para asegurar la disponibilidad de la BD antes de las migraciones
    # Porque por alguna razon a veces el contenedor de la app se inicia antes de que la BD esté lista
    command: >
      sh -c "sleep 10 && 
             npx prisma generate && 
             npx prisma db push && 
             npm run db:seed && 
             npm run start:dev"

volumes:
  postgres_data: