version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: medical-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_medica
    ports:
      - "5433:5432" # <--- YA POR FAVOR YA üíÄ, EXTERNO: 5433 (DBeaver o en PgAdmin4) | INTERNO: 5432 (API)!!!!!!!!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: medical-api-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      # La API est√° DENTRO de Docker, por eso usa el puerto interno 5432 MIENTRAS, que en host COMO DBeaver o PgAdmin4 se conecta al puerto 5433, que es el que mapea al 5432 del contenedor de la base de datos.
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestion_medica?schema=public
      JWT_SECRET: chacalito
    depends_on:
      - db
    command: > #el comando que espera a que la base de datos est√© lista antes de ejecutar las migraciones, semillas y arrancar la aplicaci√≥n.
      sh -c "sleep 10 && 
             npx prisma generate && 
             npx prisma db push && 
             npm run db:seed && 
             npm run start:dev"

volumes:
  postgres_data: